SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

BUBBLE_MIN_RADIUS = 16
BUBBLE_KINDS = 4
BUBBLE_SPAWN_RATE = 0.8
BUBBLE_MAX_RADIUS = BUBBLE_MIN_RADIUS * BUBBLE_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5